/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzgc_jni_ClusteringFunction */

#ifndef _Included_com_hzgc_jni_ClusteringFunction
#define _Included_com_hzgc_jni_ClusteringFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzgc_jni_ClusteringFunction
 * Method:    clusteringComputer
 * Signature: ([FLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hzgc_jni_ClusteringFunction_clusteringComputer
  (JNIEnv *, jclass, jfloatArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
